---
title: "individual1"
author: "Jacob Shoemaker; jshoemaker2249"
date: "2/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
HAPPY <- readRDS("HAPPY.rds")
```

##Data Cleaning
1.
```{r}

HAPPY[HAPPY == "IAP" | HAPPY == "DK" | HAPPY == "NA"] <- NA

```

2. 
```{r}
HAPPY$HAPPY <- as.factor(HAPPY$HAPPY)
HAPPY$AGE <- as.numeric(HAPPY$AGE)
HAPPY$SEX <- as.factor(HAPPY$SEX)
HAPPY$MARITAL <- as.factor(HAPPY$MARITAL)
HAPPY$AGE[HAPPY$AGE == "89 OR OLDER"] <- 89
HAPPY$DEGREE <- as.factor(HAPPY$DEGREE)
HAPPY$FINRELA <- as.factor(HAPPY$FINRELA)
HAPPY$HEALTH <- as.factor(HAPPY$HEALTH)
HAPPY$PARTYID <- as.factor(HAPPY$PARTYID)
HAPPY$POLVIEWS <- as.factor(HAPPY$POLVIEWS)
```

3. 
```{r}
HAPPY$MARITAL <- factor(HAPPY$MARITAL, levels = c("NEVER MARRIED", "MARRIED", "SEPARATED", "DIVORCED", "WIDOWED"))
HAPPY$DEGREE <- factor(HAPPY$DEGREE, levels = c("LT HIGH SCHOOL", "HIGH SCHOOL", "JUNIOR COLLEGE", "BACHELOR", "GRADUATE"))
HAPPY$FINRELA <- factor(HAPPY$FINRELA, levels = c("FAR BELOW AVERAGE", "BELOW AVERAGE", "AVERAGE", "ABOVE AVERAGE", "FAR ABOVE AVERAGE"))
HAPPY$HEALTH <- factor(HAPPY$HEALTH, levels = c("POOR", "FAIR", "GOOD", "EXCELLENT"))
HAPPY$PARTYID <- factor(HAPPY$PARTYID, levels= unique(c("STRONG DEMOCRAT", "NOT STR DEMOCRAT", "IND,NEAR DEM","INDEPENDENT", "IND,NEAR REP", "NOT STR REPUBLICAN", "STRONG REPUBLICAN", "INDEPENDENT")))
HAPPY$POLVIEWS <- factor(HAPPY$POLVIEWS, levels = c("EXTREMELY LIBERAL", "LIBERAL", "SLIGHTLY LIBERAL", "MODERATE", "SLIGHTLY CONSERVATIVE", "CONSERVATIVE", "EXTRMLY CONSERVATIVE"))
HAPPY$HAPPY <- factor(HAPPY$HAPPY, levels = c("NOT TOO HAPPY", "PRETTY HAPPY", "VERY HAPPY"))



mean(HAPPY$AGE[HAPPY$MARITAL == "NEVER MARRIED"], na.rm = TRUE)
mean(HAPPY$AGE[HAPPY$MARITAL == "MARRIED"], na.rm = TRUE)
mean(HAPPY$AGE[HAPPY$MARITAL == "SEPARATED"], na.rm = TRUE)
mean(HAPPY$AGE[HAPPY$MARITAL == "DIVORCED"], na.rm = TRUE)
mean(HAPPY$AGE[HAPPY$MARITAL == "WIDOWED"], na.rm = TRUE)

HAPPY$MARITAL <- factor(HAPPY$MARITAL, levels = c("NEVER MARRIED", "SEPARATED", "MARRIED", "DIVORCED", "WIDOWED"))
```


##Data Exploration

1. 
```{r Variable Distribution}
#distribution of sex by age
ggplot(HAPPY, aes(x=AGE, fill= SEX)) + geom_bar(na.rm = TRUE) + ggtitle("Distribution of sex by age")

#distribution of degree by sex
ggplot(HAPPY, aes(x=SEX, fill=DEGREE))+ geom_bar(na.rm = TRUE) + ggtitle("Distribution of degree by sex")
```

2.
```{r}
ggplot(HAPPY, aes(x=HAPPY, y=AGE, col=SEX)) + geom_boxplot(na.rm = TRUE)+ xlab("Happiness level")+ ggtitle("Happiness and age")


ggplot(HAPPY) + geom_mosaic(aes(x= SEX, fill=HAPPY)) + facet_grid()


```

3.
